name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - "stage-1-network/**"
      - "stage-2-addons/**"
      - "stage-3-platform/**"

  pull_request:
    branches:
      - main
    paths:
      - "stage-1-network/**"
      - "stage-2-addons/**"
      - "stage-3-platform/**"

jobs:

  detect-stage:

    runs-on: ubuntu-latest

    outputs:
      stage1: ${{ steps.filter.outputs.stage1 }}
      stage2: ${{ steps.filter.outputs.stage2 }}
      stage3: ${{ steps.filter.outputs.stage3 }}

    steps:

      - uses: actions/checkout@v4

      - id: filter

        uses: dorny/paths-filter@v3

        with:

          filters: |

            stage1:
              - 'stage-1-network/**'

            stage2:
              - 'stage-2-addons/**'

            stage3:
              - 'stage-3-platform/**'

  stage1:

    needs: detect-stage

    if: needs.detect-stage.outputs.stage1 == 'true'

    runs-on: ubuntu-latest

    defaults:

      run:

        working-directory: stage-1-network

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: terraform fmt -check

      - run: terraform validate

      - run: terraform plan

  stage2:

    needs: detect-stage

    if: needs.detect-stage.outputs.stage2 == 'true'

    runs-on: ubuntu-latest

    defaults:

      run:

        working-directory: stage-2-addons

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: terraform fmt -check

      - run: terraform validate

      - run: terraform plan

  stage3:

    needs: detect-stage

    if: needs.detect-stage.outputs.stage3 == 'true'

    runs-on: ubuntu-latest

    defaults:

      run:

        working-directory: stage-3-platform

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: terraform fmt -check

      - run: terraform validate

      - run: terraform plan